export enum Role {
  // platform users
  ROLE_PLATFORM_ADMIN = 'ROLE_PLATFORM_ADMIN',
  ROLE_PLATFORM_MANAGER = 'ROLE_PLATFORM_MANAGER',
  ROLE_PLATFORM_CLIENT = 'ROLE_PLATFORM_CLIENT', //readonly

  // platform technical role
  ROLE_PLATFORM_SUPPORT = 'ROLE_PLATFORM_SUPPORT',

  // platform resource-specific roles (for Account operations)
  ROLE_PLATFORM_ACCOUNT_RW = 'ROLE_PLATFORM_ACCOUNT_RW',
  ROLE_PLATFORM_ACCOUNT_RO = 'ROLE_PLATFORM_ACCOUNT_RO',

  // cms base users
  ROLE_CMS_ADMIN = 'ROLE_CMS_ADMIN',
  ROLE_CMS_EDITOR = 'ROLE_CMS_EDITOR',
  ROLE_CMS_USER = 'ROLE_CMS_USER',

  // business users
  PRODUCT_ADMIN = 'PRODUCT_ADMIN',
  MANAGER_BUSINESS_USERS = 'MANAGER_BUSINESS_USERS',
  MANAGER_USERS = 'MANAGER_USERS',
  PRODUCT_USER = 'PRODUCT_USER', //Пользователь компании
  MODERATOR = 'ROLE_UGC_MODERATOR',
  MODERATOR_QNA = 'ROLE_UGC_MODERATOR_QNA',
  MODERATOR_FEEDBACK = 'ROLE_UGC_MODERATOR_FEEDBACK',
  MODERATOR_COMPLAINT = 'ROLE_UGC_MODERATOR_COMPLAINT',
  MODERATOR_COMMENT = 'ROLE_UGC_MODERATOR_COMMENT',
  MODERATOR_FORECAST = 'ROLE_UGC_MODERATOR_FORECAST',

  // partner user
  PARTNER = 'ROLE_UGC_PARTNER',

  // spa user
  USERS_ROLE = 'ROLE_SITE_USER',

  // custom strapi role
  ROLE_CMS_TRANSIENT = 'ROLE_CMS_TRANSIENT',

  // deprecated
  ROLE_SS_EDITOR = 'ROLE_SS_EDITOR',
  ROLE_SS_PUB_EDITOR = 'ROLE_SS_PUB_EDITOR',
  ROLE_SS_SEO = 'ROLE_SS_SEO',
  ROLE_SS_BON_EDITOR = 'ROLE_SS_BON_EDITOR',
}






